# load dependencies
#----------------------------------------------------------------------------------------
if (!existsFunction ('%>%')) library ('tidyverse') # to generally process data
if (!existsFunction ('as_date')) library ('lubridate') # to use as_date function
if (!existsFunction ('nc_open')) library ('ncdf4')  # to manipulate netcdf files (climate)
if (!exists ('rwEYSTI')) source ('wrangleGrowthData.R') # to load ring width data from all sites
if (!existsFunction ('thornthwaite')) library ('SPEI') # to calculate the potential evapotranspiration
if (!existsFunction ('pdsi')) library ('scPDSI') # to calculate the scPDSI

# read summarised monthly data as generated by BioSIM 
#----------------------------------------------------------------------------------------
tmp1 <- read_csv ("../data/climate/Export (SummariseOutputs1900-1950).csv",
                  col_types = cols ())
tmp2 <- read_csv ("../data/climate/Export (SummariseOutputs1951-1980).csv",
                  col_types = cols ()) %>% select (1:22)
tmp3 <- read_csv ("../data/climate/Export (SummariseOutputs1981-2020).csv",
                  col_types = cols ()) %>% select (1:22)
tmp <- rbind (tmp1, tmp2, tmp3) %>% select (-c(Replication, P, Name, Country, State)) %>% 
  arrange (KeyID, Latitude, Longitude, Year, Month) %>% 
  mutate (date = paste (lubridate::month (as.numeric (Month), 
                                          label = TRUE, 
                                          abbr = TRUE), 
                        Year, sep = "-"))

# pivot data wide to format used by Drew's code
#-------------------------------------------------------------------------------
siteTempData <- tmp %>% 
  pivot_wider (id_cols = 1:3,
               values_from = `Air Temperature`,
               names_from = date) %>% 
  rename (site = "KeyID") %>% select (-Latitude, -Longitude)
sitePrecData <- tmp %>% 
  pivot_wider (id_cols = 1:3,
               values_from = `Total Precipitation`,
               names_from = date) %>% 
  rename (site = "KeyID") %>% select (-Latitude, -Longitude)

# combine siteMetaData with climate data
#-------------------------------------------------------------------------------
siteTempData <- full_join (siteMetaData, siteTempData, by = c ("site"))
sitePrecData <- full_join (siteMetaData, sitePrecData, by = c ("site"))

# calculate monthly self-calibrating Palmer Drought Severity Index  
#-------------------------------------------------------------------------------
for (s in 1:dim (siteMetaData) [1]) {
  
  # estimate potential evapotransporation [mm]
  #-----------------------------------------------------------------------------
  PET <- thornthwaite (Tave = t (siteTempData [s, 18:1469]), 
                       lat = siteMetaData$lat [s],
                       na.rm = TRUE)
  PET <- as.numeric (PET)
  
  # calculate self-calibrating Palmer Drought Severity Index
  #-----------------------------------------------------------------------------
  scPDSI <- pdsi (P = unlist (sitePrecData [s, 18:1469]),
                  PE = PET,
                  sc = TRUE)
  
  # append PDSI data
  #-----------------------------------------------------------------------------
  if (s == 1) {
    sitePDSIData <- as_tibble (t (scPDSI$X))
  } else {
    sitePDSIData <- add_row (sitePDSIData, as_tibble (t (scPDSI$X)))
  }
}

# change names of monthly scPDSI data for consistency with temperature and 
# precipitation data
#-------------------------------------------------------------------------------
names (sitePDSIData) <- paste (
  rep (c ("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"), 120),
  rep (1900:2020, each = 12), sep = "-")

# add siteMetaData to sitePDSIData to have same format as siteTempData and sitePrecData
#-------------------------------------------------------------------------------
sitePDSIData <- add_column (siteMetaData, sitePDSIData)

# write processed climate variables
#-------------------------------------------------------------------------------
write_csv (siteTempData, "../data/climate/processed/siteTempData.csv")
write_csv (sitePrecData, "../data/climate/processed/sitePrecData.csv")
write_csv (sitePDSIData, "../data/climate/processed/sitePDSIData.csv")

# clean-up 
#-------------------------------------------------------------------------------
rm (tmp, tmp1, tmp2, tmp3, PET, scPDSI, s)
